In [1]:
import cupy as cp

print("CuPy Version:", cp.__version__)

CuPy Version: 14.0.1


In [2]:
import numpy as np

N = 1_000_000  # 1 Million elements

data = np.random.randint(
    0,
    1000000,
    size=N,
    dtype=np.int32
)

print("Dataset Size:", len(data))
print("First 10 values:")
print(data[:10])

Dataset Size: 1000000
First 10 values:
[  8102 990526 117568 183947 636016 663903 569842 816461 720368 420411]


In [3]:
import cupy as cp

gpu_data = cp.asarray(data)

print("Data transferred to GPU")
print("GPU Array Shape:", gpu_data.shape)

Data transferred to GPU
GPU Array Shape: (1000000,)


In [4]:
import time

start_gpu = time.time()

gpu_sorted = cp.sort(gpu_data)

cp.cuda.Stream.null.synchronize()

end_gpu = time.time()

gpu_time = end_gpu - start_gpu

print("GPU Sorting Time:", gpu_time, "seconds")

GPU Sorting Time: 0.6536271572113037 seconds


In [5]:
sorted_cpu = cp.asnumpy(gpu_sorted)

print("First 10 Sorted Values:")
print(sorted_cpu[:10])

print("\nLast 10 Sorted Values:")
print(sorted_cpu[-10:])

print("\nArray Sorted:",
      np.all(sorted_cpu[:-1] <= sorted_cpu[1:]))

First 10 Sorted Values:
[0 1 1 1 2 3 4 6 6 8]

Last 10 Sorted Values:
[999991 999993 999994 999996 999996 999998 999999 999999 999999 999999]

Array Sorted: True


In [6]:
import time

start_cpu = time.time()

cpu_sorted = np.sort(data)

end_cpu = time.time()

cpu_time = end_cpu - start_cpu

print("CPU Sorting Time:", cpu_time, "seconds")

CPU Sorting Time: 0.01484990119934082 seconds
